import 'package:flutter/material.dart';

import 'quote.dart';

class Quotes with ChangeNotifier {
  List<Quote> _quotes = [
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "It’s not about ideas. It’s about making ideas happen.",
      authorName: "Scott Belsky",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Always deliver more than expected.",
      authorName: "Larry Page",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Anyone who has never made a mistake has never anything new.",
      authorName: "Albert Einstein",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote:
          "If people are doubting how far you can go, go so far that you can't hear them anymore.",
      authorName: "Michele Ruiz",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "They don't believe in you until it's too late.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Age is just a number.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "You get paid for your value.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "They don't believe in you until it's too late.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote:
          "What's happening in your life is a result of what's happening in your mind.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Be the person who brings light into the World.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Nobody is born racist, it is taught we need to stop teaching it.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Do what others don't today to do what others can't twomarrow.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Whatever you do give it your all.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Time is something you either use or abuse.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Life is 10% what happens to you and 90% how you react to it.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Life doesn't give a purpose. We give life a purpose.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: true,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote:
          "Your life is your message to the World. Make sure it's inspiring.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Mind is like an umbrella. It's most useful when it's open.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Risk is the price you pay for oppurtunity.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "We only regret the changes we didn't take.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Give, even if you have a little.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote:
          "People don't decide their future they decide their habits that decide their future.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Atitude determines success.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "A bad system can destroy good people.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Difficult doesn't mean impossible.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Talk less. Think more. Work harded.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Simplify your life. Learn to say 'No'.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Never get so busy.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Work smart not hard.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote:
          "People who defend your name when you're not around are the most loyal friends you could never get.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote:
          "No matter how much effort you put in if you use the wrong tools, you won't make it.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Never get so busy",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote:
          "You don't get rick for having ideas you get rich making them reality.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Finding the right answers to progress is rarely simple.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Stop seeking validation from others.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Train your mind to see the good in everything.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "If you work just for money, you will never make it.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Don't wait for oppertunity, create it.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Keep your eyes on your end goal.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote:
          "Those who help others in times of struggle will be rewarded greatly in times of prosperity.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "School don't want you to think creatively.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "The most valueable gift you can receive is an honest friend.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Knowing is not enough, we must apply!",
      authorName: "Johhann Wolfgang",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote:
          "you were not born a winner, and you were not born a loser. You are what you make yourself be.",
      authorName: "Lou Holtz",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote:
          "There are two kinds of failures: those who thought and never did, and those who did and never thought.",
      authorName: "Laurence J. Peter",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Your best teacher is your last mistake.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Overthinking will destroy you.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote:
          "Never make a decision when you are angry, never make a promise when you are happy.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Never live in past but always learn from it.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Never forget who was with you when you had nothing",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote:
          "Life's short. Spend it with people who make you laugh and feel loved.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote:
          "4 things you can't get back: 1- The stone after it's thrown.   2- The word after it's said.    3- The occasion after it's missed.   4- The time after it's gone.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Stop chasing wrong one, the right one won't run.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Most important rule of life: Do what makes you happy.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "I respect people that tell me truth, no matter how har it is.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Take risks, Don't be afraid of failures, learn from them.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Every one wants happiness. No one wants pain. But you can't have a rainbow, without little rain.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Every night before you go to bed you should ask yourself, 'Am I better than I was yesterday?'",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "The past is behind, learn from it. The future is ahead, prepare for it. The present id here, live it.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
    Quote(
      addedBy: "Hassan Ur Rahman",
      quote: "Take every chance you get in life, because some things only happen once.",
      authorName: "Unknown",
      date: DateTime.now().toString(),
      time: DateTime.now().toString(),
      likes: 0,
      dislikes: 0,
      shares: 0,
      favorite: false,
    ),
  ];

  List<Quote> get quotes {
    return [..._quotes];
  }

  List<Quote> _favQuotes = [];

  List<Quote> get favQuotes {
    return [..._favQuotes];
  }

  notifyListeners();

  dynamic deleteQuote(quote, BuildContext context) {
    return showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        elevation: Theme.of(context).dialogTheme.elevation,
        title: Text(
          "Confirm",
          style: Theme.of(context).dialogTheme.contentTextStyle,
        ),
        content: Text(
          "Are You Sure?",
          style: Theme.of(context).dialogTheme.contentTextStyle,
        ),
        actions: <Widget>[
          FlatButton(
            child: Text(
              "No",
              style: Theme.of(context).dialogTheme.contentTextStyle,
            ),
            onPressed: () {
              Navigator.of(ctx).pop();
            },
          ),
          FlatButton(
            child: Text(
              "Yes",
              style: Theme.of(context).dialogTheme.contentTextStyle,
            ),
            onPressed: () {
              _quotes.remove(quote);
              Navigator.of(ctx).pop();
              notifyListeners();
            },
          ),
        ],
      ),
    );
  }

  dynamic addQuote(String qtAddedBy, String qtQuote, String qtAuthorName,
      String qtDate, String qtTime) {
    final newQuote = Quote(
      addedBy: qtAddedBy,
      quote: qtQuote,
      authorName: qtAuthorName,
      date: qtDate,
      time: qtTime,
    );
    _quotes.add(
      newQuote,
    );

    notifyListeners();
  }
}
